# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MsFPOP_cpp <- function(y, beta, alpha, sampling_method, sampling_method_parameter, wt) {
    .Call('_MsFPOP_MsFPOP_cpp', PACKAGE = 'MsFPOP', y, beta, alpha, sampling_method, sampling_method_parameter, wt)
}

MsPELT_cpp <- function(y, beta, alpha, wt) {
    .Call('_MsFPOP_MsPELT_cpp', PACKAGE = 'MsFPOP', y, beta, alpha, wt)
}

